yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import Truncator
from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Создаем класс для модели группы."""

    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Короткая ссылка')
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self) -> str:
        """Функция для вывода на печать."""
        return self.title

    class Meta:
        verbose_name_plural = 'Сообщества'
        verbose_name = 'Сообщество'


class Post(CreatedModel):
    """Создаем класс для модели Post."""

    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Вы можете выбрать группу для вашего поста.'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Выберете картинку для Вашего поста.'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self) -> str:
        """Функция для вывода на печать."""
        return Truncator(self.text).chars(30)


class Comment(CreatedModel):
    """Создаем класс для модели Comment."""

    text = models.TextField('Текст комментария',
                            help_text='Напишите Ваш комментарий в это поле.')
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'

    def __str__(self) -> str:
        """Функция для вывода на печать."""
        return Truncator(self.text).chars(30)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'

    )

    class Meta:
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписка'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from typing import Type, Union

from django.contrib.auth.decorators import login_required
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow
from .utils import pag_posts


def index(request: Type[HttpRequest]) -> Type[HttpResponse]:
    """Определяем функцию для главной страницы."""
    post_list: Type[QuerySet] = Post.objects.select_related('author', 'group')
    page_obj = pag_posts(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request: Type[HttpRequest], slug: str) -> Type[HttpResponse]:
    """Определяем функцию для страницы групп."""
    group = get_object_or_404(Group, slug=slug)
    post_list: Type[QuerySet] = group.posts.select_related('author', 'group')
    page_obj = pag_posts(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request: Type[HttpRequest], username: str) -> Type[HttpResponse]:
    """Профиль автора."""
    author = get_object_or_404(User, username=username)
    post_list: Type[QuerySet] = author.posts.select_related('author', 'group')
    page_obj = pag_posts(request, post_list)
    user = request.user
    show_follow = request.user.is_authenticated and request.user != author
    following = request.user.is_authenticated and Follow.objects.filter(
        user=user, author=author).exists()
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
        'show_follow': show_follow
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request: Type[HttpRequest],
                post_id: int) -> Type[HttpResponse]:
    """Детализация поста."""
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.select_related()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request: Type[HttpRequest]) -> (
        Union[Type[HttpResponse],
              Type[HttpResponseRedirect]]):
    """Создаем новый пост."""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not request.method == 'POST':
        return render(request, 'posts/create_post.html', {'form': form})
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author.username)


@login_required
def post_edit(request: Type[HttpRequest],
              post_id: int) -> (Union[Type[HttpResponse],
                                      Type[HttpResponseRedirect]]):
    """Редактируем пост."""
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if not request.user.username == post.author.username:
        return redirect('posts:post_detail', post.id)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {
            'form': form,
            'is_edit': True
        })
    form.save()
    return redirect('posts:post_detail', post.id)


@login_required
def add_comment(request: Type[HttpRequest],
                post_id: int) -> Type[HttpResponse]:
    """Создаем комментарий к посту."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request: Type[HttpRequest]) -> Type[HttpResponse]:
    post_list = Post.objects.filter(
        author__following__user=request.user
    )
    page_obj = pag_posts(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(
        request: Type[HttpRequest], username: str
) -> Type[HttpResponse]:
    user = request.user
    author = get_object_or_404(User, username=username)
    if not Follow.objects.filter(
            user=user, author=author
    ).exists() and not user == author:
        Follow.objects.create(user=user, author=author)
    return redirect(reverse('posts:profile', args=(username,)))


@login_required
def profile_unfollow(
        request: Type[HttpRequest], username: str
) -> Type[HttpResponse]:
    user = request.user
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=user, author=author)
    if follow.exists():
        follow.delete()
    return redirect(reverse('posts:profile', args=(username,)))

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %} Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактируемый пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label>
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                <small class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления избранных авторов
{% endblock %}
{% block content %}
   {% include 'posts/includes/switcher.html' %}
    <h1>Последние обновления избранных авторов</h1>
    {% for post in page_obj %}
      {% include 'posts/posts.html' with show_group=True show_profile=True %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ group.title }}
{% endblock %}

{% block content %}
  <h1>
    {{ group.title }}
  </h1>
  <p>
    {{ group.description }}
  </p>

  {% for post in page_obj %}
    {% include 'posts/posts.html' with show_profile=True %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% load cache %}
  {% cache 20 index_page %}
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      {% include 'posts/posts.html' with show_group=True show_profile=True %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи
              группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.username }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{ post.author.posts.count }}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if user == post.author %}
        <a class="btn btn-outline-secondary btn-sm"
           href="{% url 'posts:post_edit' post.id %}">редактировать пост</a>
      {% endif %}
      </p>
      {% load user_filters %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %}
    </article>
  </div>

{% endblock %}

yatube/templates/posts/posts.html
{% load thumbnail %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
    {% if show_profile %}
      <a href="{% url 'posts:profile' post.author.username %}">все посты
        пользователя</a>
    {% endif %}

  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>{{ post.text }}</p>
<p><a href="{% url 'posts:post_detail' post.id %}">подробная
  информация</a></p>
{% if post.group and show_group %}
  <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы
    #{{ post.group.title }}</a>
{% endif %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if show_follow %}
      {% if following %}
        <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}"
            role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}"
            role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    {% include 'posts/posts.html' with show_group=True %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}